name: flutter_scan_bluetooth
description: Flutter plugin to scan Bluetooth devices.
version: 1.1.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

flutter:
  plugin:
    platforms:
      android:
        package: com.f2fk.flutterscanbluetooth
        pluginClass: FlutterScanBluetoothPlugin
      ios:
        pluginClass: FlutterScanBluetoothPlugin

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"
